name: Build

on:
  push:
    branches:
      - main
      - feature/development-app
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para que Sonar analice bien el historial

      # Instalar Java y Gradle si no estuviera ya
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construir el proyecto Android
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Escaneo de SonarCloud
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        with:
          args: >
            -Dsonar.projectKey=MarcosGomezVega_TFG-App-IA-IncidenciasViales
            -Dsonar.organization=marcosgomezvega
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectName=TFG-App-IA-IncidenciasViales
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=app/src/main/java
            -Dsonar.inclusions=**/*.java
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.java.binaries=app/build/intermediates/javac/debug/classes
